name: Deploy Vercel Chatbot API

on:
  push:
    branches:
      - main
    paths:
      - 'vercel-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Vercel CLI locally
        run: npm install vercel@latest --no-save
        working-directory: ./vercel-api

      - name: Pull, Build, and Deploy to Vercel
        run: |
          npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel build --prod --force --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./vercel-api
        env:
          VERCEL_ORG_ID: '${{ secrets.VERCEL_ORG_ID }}'
          VERCEL_PROJECT_ID: '${{ secrets.VERCEL_PROJECT_ID }}'
